#nullable enable annotations

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/CollectionsMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufNullificator.Tests.Protos {

  /// <summary>Holder for reflection information generated from Protos/CollectionsMessage.proto</summary>
  public static partial class CollectionsMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/CollectionsMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CollectionsMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9Qcm90b3MvQ29sbGVjdGlvbnNNZXNzYWdlLnByb3RvEiFQcm90b2J1Zk51",
            "bGxpZmljYXRvci5UZXN0cy5Qcm90b3MaHmdvb2dsZS9wcm90b2J1Zi93cmFw",
            "cGVycy5wcm90byKABgoSQ29sbGVjdGlvbnNNZXNzYWdlElgKCnN0cmluZ19t",
            "YXAYASADKAsyRC5Qcm90b2J1Zk51bGxpZmljYXRvci5UZXN0cy5Qcm90b3Mu",
            "Q29sbGVjdGlvbnNNZXNzYWdlLlN0cmluZ01hcEVudHJ5El8KDmludF9zdHJp",
            "bmdfbWFwGAIgAygLMkcuUHJvdG9idWZOdWxsaWZpY2F0b3IuVGVzdHMuUHJv",
            "dG9zLkNvbGxlY3Rpb25zTWVzc2FnZS5JbnRTdHJpbmdNYXBFbnRyeRIXCg9y",
            "ZXBlYXRlZF9zdHJpbmcYAyADKAkSFAoMcmVwZWF0ZWRfaW50GAQgAygFElEK",
            "EnJlY3Vyc2l2ZV9yZXBlYXRlZBgFIAMoCzI1LlByb3RvYnVmTnVsbGlmaWNh",
            "dG9yLlRlc3RzLlByb3Rvcy5Db2xsZWN0aW9uc01lc3NhZ2USOwoVcmVwZWF0",
            "ZWRfc3RyaW5nX3ZhbHVlGAYgAygLMhwuZ29vZ2xlLnByb3RvYnVmLlN0cmlu",
            "Z1ZhbHVlEjcKEnJlcGVhdGVkX2ludF92YWx1ZRgHIAMoCzIbLmdvb2dsZS5w",
            "cm90b2J1Zi5JbnQzMlZhbHVlEmMKEHN0cmluZ192YWx1ZV9tYXAYCCADKAsy",
            "SS5Qcm90b2J1Zk51bGxpZmljYXRvci5UZXN0cy5Qcm90b3MuQ29sbGVjdGlv",
            "bnNNZXNzYWdlLlN0cmluZ1ZhbHVlTWFwRW50cnkSFgoOcmVwZWF0ZWRfYnl0",
            "ZXMYCSADKAwaMAoOU3RyaW5nTWFwRW50cnkSCwoDa2V5GAEgASgJEg0KBXZh",
            "bHVlGAIgASgJOgI4ARozChFJbnRTdHJpbmdNYXBFbnRyeRILCgNrZXkYASAB",
            "KAUSDQoFdmFsdWUYAiABKAk6AjgBGlMKE1N0cmluZ1ZhbHVlTWFwRW50cnkS",
            "CwoDa2V5GAEgASgJEisKBXZhbHVlGAIgASgLMhwuZ29vZ2xlLnByb3RvYnVm",
            "LlN0cmluZ1ZhbHVlOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNullificator.Tests.Protos.CollectionsMessage), global::ProtobufNullificator.Tests.Protos.CollectionsMessage.Parser, new[]{ "StringMap", "IntStringMap", "RepeatedString", "RepeatedInt", "RecursiveRepeated", "RepeatedStringValue", "RepeatedIntValue", "StringValueMap", "RepeatedBytes" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CollectionsMessage : pb::IMessage<CollectionsMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CollectionsMessage> _parser = new pb::MessageParser<CollectionsMessage>(() => new CollectionsMessage());
    private pb::UnknownFieldSet? _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CollectionsMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNullificator.Tests.Protos.CollectionsMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollectionsMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollectionsMessage(CollectionsMessage other) : this() {
      stringMap_ = other.stringMap_.Clone();
      intStringMap_ = other.intStringMap_.Clone();
      repeatedString_ = other.repeatedString_.Clone();
      repeatedInt_ = other.repeatedInt_.Clone();
      recursiveRepeated_ = other.recursiveRepeated_.Clone();
      repeatedStringValue_ = other.repeatedStringValue_.Clone();
      repeatedIntValue_ = other.repeatedIntValue_.Clone();
      stringValueMap_ = other.stringValueMap_.Clone();
      repeatedBytes_ = other.repeatedBytes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CollectionsMessage Clone() {
      return new CollectionsMessage(this);
    }

    /// <summary>Field number for the "string_map" field.</summary>
    public const int StringMapFieldNumber = 1;
    private static readonly pbc::MapField<string, string>.Codec _map_stringMap_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 10);
    private readonly pbc::MapField<string, string> stringMap_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> StringMap {
      get { return stringMap_; }
    }

    /// <summary>Field number for the "int_string_map" field.</summary>
    public const int IntStringMapFieldNumber = 2;
    private static readonly pbc::MapField<int, string>.Codec _map_intStringMap_codec
        = new pbc::MapField<int, string>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForString(18, ""), 18);
    private readonly pbc::MapField<int, string> intStringMap_ = new pbc::MapField<int, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, string> IntStringMap {
      get { return intStringMap_; }
    }

    /// <summary>Field number for the "repeated_string" field.</summary>
    public const int RepeatedStringFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_repeatedString_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> repeatedString_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RepeatedString {
      get { return repeatedString_; }
    }

    /// <summary>Field number for the "repeated_int" field.</summary>
    public const int RepeatedIntFieldNumber = 4;
    private static readonly pb::FieldCodec<int> _repeated_repeatedInt_codec
        = pb::FieldCodec.ForInt32(34);
    private readonly pbc::RepeatedField<int> repeatedInt_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> RepeatedInt {
      get { return repeatedInt_; }
    }

    /// <summary>Field number for the "recursive_repeated" field.</summary>
    public const int RecursiveRepeatedFieldNumber = 5;
    private static readonly pb::FieldCodec<global::ProtobufNullificator.Tests.Protos.CollectionsMessage> _repeated_recursiveRepeated_codec
        = pb::FieldCodec.ForMessage(42, global::ProtobufNullificator.Tests.Protos.CollectionsMessage.Parser);
    private readonly pbc::RepeatedField<global::ProtobufNullificator.Tests.Protos.CollectionsMessage> recursiveRepeated_ = new pbc::RepeatedField<global::ProtobufNullificator.Tests.Protos.CollectionsMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtobufNullificator.Tests.Protos.CollectionsMessage> RecursiveRepeated {
      get { return recursiveRepeated_; }
    }

    /// <summary>Field number for the "repeated_string_value" field.</summary>
    public const int RepeatedStringValueFieldNumber = 6;
    private static readonly pb::FieldCodec<string> _repeated_repeatedStringValue_codec
        = pb::FieldCodec.ForClassWrapper<string>(50);
    private readonly pbc::RepeatedField<string> repeatedStringValue_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> RepeatedStringValue {
      get { return repeatedStringValue_; }
    }

    /// <summary>Field number for the "repeated_int_value" field.</summary>
    public const int RepeatedIntValueFieldNumber = 7;
    private static readonly pb::FieldCodec<int?> _repeated_repeatedIntValue_codec
        = pb::FieldCodec.ForStructWrapper<int>(58);
    private readonly pbc::RepeatedField<int?> repeatedIntValue_ = new pbc::RepeatedField<int?>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int?> RepeatedIntValue {
      get { return repeatedIntValue_; }
    }

    /// <summary>Field number for the "string_value_map" field.</summary>
    public const int StringValueMapFieldNumber = 8;
    private static readonly pbc::MapField<string, string>.Codec _map_stringValueMap_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForClassWrapper<string>(18), 66);
    private readonly pbc::MapField<string, string> stringValueMap_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> StringValueMap {
      get { return stringValueMap_; }
    }

    /// <summary>Field number for the "repeated_bytes" field.</summary>
    public const int RepeatedBytesFieldNumber = 9;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_repeatedBytes_codec
        = pb::FieldCodec.ForBytes(74);
    private readonly pbc::RepeatedField<pb::ByteString> repeatedBytes_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> RepeatedBytes {
      get { return repeatedBytes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object? other) {
      return Equals(other as CollectionsMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CollectionsMessage? other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!StringMap.Equals(other.StringMap)) return false;
      if (!IntStringMap.Equals(other.IntStringMap)) return false;
      if(!repeatedString_.Equals(other.repeatedString_)) return false;
      if(!repeatedInt_.Equals(other.repeatedInt_)) return false;
      if(!recursiveRepeated_.Equals(other.recursiveRepeated_)) return false;
      if(!repeatedStringValue_.Equals(other.repeatedStringValue_)) return false;
      if(!repeatedIntValue_.Equals(other.repeatedIntValue_)) return false;
      if (!StringValueMap.Equals(other.StringValueMap)) return false;
      if(!repeatedBytes_.Equals(other.repeatedBytes_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= StringMap.GetHashCode();
      hash ^= IntStringMap.GetHashCode();
      hash ^= repeatedString_.GetHashCode();
      hash ^= repeatedInt_.GetHashCode();
      hash ^= recursiveRepeated_.GetHashCode();
      hash ^= repeatedStringValue_.GetHashCode();
      hash ^= repeatedIntValue_.GetHashCode();
      hash ^= StringValueMap.GetHashCode();
      hash ^= repeatedBytes_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      stringMap_.WriteTo(output, _map_stringMap_codec);
      intStringMap_.WriteTo(output, _map_intStringMap_codec);
      repeatedString_.WriteTo(output, _repeated_repeatedString_codec);
      repeatedInt_.WriteTo(output, _repeated_repeatedInt_codec);
      recursiveRepeated_.WriteTo(output, _repeated_recursiveRepeated_codec);
      repeatedStringValue_.WriteTo(output, _repeated_repeatedStringValue_codec);
      repeatedIntValue_.WriteTo(output, _repeated_repeatedIntValue_codec);
      stringValueMap_.WriteTo(output, _map_stringValueMap_codec);
      repeatedBytes_.WriteTo(output, _repeated_repeatedBytes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      stringMap_.WriteTo(ref output, _map_stringMap_codec);
      intStringMap_.WriteTo(ref output, _map_intStringMap_codec);
      repeatedString_.WriteTo(ref output, _repeated_repeatedString_codec);
      repeatedInt_.WriteTo(ref output, _repeated_repeatedInt_codec);
      recursiveRepeated_.WriteTo(ref output, _repeated_recursiveRepeated_codec);
      repeatedStringValue_.WriteTo(ref output, _repeated_repeatedStringValue_codec);
      repeatedIntValue_.WriteTo(ref output, _repeated_repeatedIntValue_codec);
      stringValueMap_.WriteTo(ref output, _map_stringValueMap_codec);
      repeatedBytes_.WriteTo(ref output, _repeated_repeatedBytes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += stringMap_.CalculateSize(_map_stringMap_codec);
      size += intStringMap_.CalculateSize(_map_intStringMap_codec);
      size += repeatedString_.CalculateSize(_repeated_repeatedString_codec);
      size += repeatedInt_.CalculateSize(_repeated_repeatedInt_codec);
      size += recursiveRepeated_.CalculateSize(_repeated_recursiveRepeated_codec);
      size += repeatedStringValue_.CalculateSize(_repeated_repeatedStringValue_codec);
      size += repeatedIntValue_.CalculateSize(_repeated_repeatedIntValue_codec);
      size += stringValueMap_.CalculateSize(_map_stringValueMap_codec);
      size += repeatedBytes_.CalculateSize(_repeated_repeatedBytes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CollectionsMessage? other) {
      if (other == null) {
        return;
      }
      stringMap_.MergeFrom(other.stringMap_);
      intStringMap_.MergeFrom(other.intStringMap_);
      repeatedString_.Add(other.repeatedString_);
      repeatedInt_.Add(other.repeatedInt_);
      recursiveRepeated_.Add(other.recursiveRepeated_);
      repeatedStringValue_.Add(other.repeatedStringValue_);
      repeatedIntValue_.Add(other.repeatedIntValue_);
      stringValueMap_.MergeFrom(other.stringValueMap_);
      repeatedBytes_.Add(other.repeatedBytes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            stringMap_.AddEntriesFrom(input, _map_stringMap_codec);
            break;
          }
          case 18: {
            intStringMap_.AddEntriesFrom(input, _map_intStringMap_codec);
            break;
          }
          case 26: {
            repeatedString_.AddEntriesFrom(input, _repeated_repeatedString_codec);
            break;
          }
          case 34:
          case 32: {
            repeatedInt_.AddEntriesFrom(input, _repeated_repeatedInt_codec);
            break;
          }
          case 42: {
            recursiveRepeated_.AddEntriesFrom(input, _repeated_recursiveRepeated_codec);
            break;
          }
          case 50: {
            repeatedStringValue_.AddEntriesFrom(input, _repeated_repeatedStringValue_codec);
            break;
          }
          case 58: {
            repeatedIntValue_.AddEntriesFrom(input, _repeated_repeatedIntValue_codec);
            break;
          }
          case 66: {
            stringValueMap_.AddEntriesFrom(input, _map_stringValueMap_codec);
            break;
          }
          case 74: {
            repeatedBytes_.AddEntriesFrom(input, _repeated_repeatedBytes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            stringMap_.AddEntriesFrom(ref input, _map_stringMap_codec);
            break;
          }
          case 18: {
            intStringMap_.AddEntriesFrom(ref input, _map_intStringMap_codec);
            break;
          }
          case 26: {
            repeatedString_.AddEntriesFrom(ref input, _repeated_repeatedString_codec);
            break;
          }
          case 34:
          case 32: {
            repeatedInt_.AddEntriesFrom(ref input, _repeated_repeatedInt_codec);
            break;
          }
          case 42: {
            recursiveRepeated_.AddEntriesFrom(ref input, _repeated_recursiveRepeated_codec);
            break;
          }
          case 50: {
            repeatedStringValue_.AddEntriesFrom(ref input, _repeated_repeatedStringValue_codec);
            break;
          }
          case 58: {
            repeatedIntValue_.AddEntriesFrom(ref input, _repeated_repeatedIntValue_codec);
            break;
          }
          case 66: {
            stringValueMap_.AddEntriesFrom(ref input, _map_stringValueMap_codec);
            break;
          }
          case 74: {
            repeatedBytes_.AddEntriesFrom(ref input, _repeated_repeatedBytes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
