using Microsoft.Build.Framework;

namespace ProtobufNrtAnnotator;

public class NrtAnnotateProtobufFiles : Microsoft.Build.Utilities.Task
{
    [Required]
    public ITaskItem[] Files { get; set; } = [];

    public override bool Execute()
    {
        foreach (var filePath in Files.Select(x => x.ItemSpec))
        {
            if (!File.Exists(filePath))
            {
                continue;
            }
            var code = File.ReadAllText(filePath);

            // Only process files that look like protobuf-generated code
            if (!code.Contains("Generated by the protocol buffer compiler"))
            {
                Log.LogMessage($"Skipping {filePath} (not protobuf-generated)");
                continue;
            }

            Log.LogMessage($"Processing {filePath}...");

            var newCode = Runner.ProcessContent(code);
            File.WriteAllText(filePath, newCode);
        }

        return true;
    }
}