#nullable enable annotations

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/BytesMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufNrtAnnotator.Tests.Protos {

  /// <summary>Holder for reflection information generated from Protos/BytesMessage.proto</summary>
  public static partial class BytesMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/BytesMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BytesMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlQcm90b3MvQnl0ZXNNZXNzYWdlLnByb3RvEiFQcm90b2J1Zk5ydEFubm90",
            "YXRvci5UZXN0cy5Qcm90b3MaHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVycy5w",
            "cm90byLwAQoMQnl0ZXNNZXNzYWdlEhMKC2J5dGVzX2ZpZWxkGAEgASgMEjAK",
            "C2J5dGVzX3ZhbHVlGAIgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkJ5dGVzVmFs",
            "dWUSFgoOcmVwZWF0ZWRfYnl0ZXMYAyADKAwSUAoJbWFwX2J5dGVzGAQgAygL",
            "Mj0uUHJvdG9idWZOcnRBbm5vdGF0b3IuVGVzdHMuUHJvdG9zLkJ5dGVzTWVz",
            "c2FnZS5NYXBCeXRlc0VudHJ5Gi8KDU1hcEJ5dGVzRW50cnkSCwoDa2V5GAEg",
            "ASgJEg0KBXZhbHVlGAIgASgMOgI4AWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNrtAnnotator.Tests.Protos.BytesMessage), global::ProtobufNrtAnnotator.Tests.Protos.BytesMessage.Parser, new[]{ "BytesField", "BytesValue", "RepeatedBytes", "MapBytes" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, })
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class BytesMessage : pb::IMessage<BytesMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<BytesMessage> _parser = new pb::MessageParser<BytesMessage>(() => new BytesMessage());
    private pb::UnknownFieldSet? _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<BytesMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNrtAnnotator.Tests.Protos.BytesMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BytesMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BytesMessage(BytesMessage other) : this() {
      bytesField_ = other.bytesField_;
      BytesValue = other.BytesValue;
      repeatedBytes_ = other.repeatedBytes_.Clone();
      mapBytes_ = other.mapBytes_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public BytesMessage Clone() {
      return new BytesMessage(this);
    }

    /// <summary>Field number for the "bytes_field" field.</summary>
    public const int BytesFieldFieldNumber = 1;
    private pb::ByteString bytesField_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString BytesField {
      get { return bytesField_; }
      set {
        bytesField_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "bytes_value" field.</summary>
    public const int BytesValueFieldNumber = 2;
    private static readonly pb::FieldCodec<pb::ByteString> _single_bytesValue_codec = pb::FieldCodec.ForClassWrapper<pb::ByteString>(18);
    private pb::ByteString bytesValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString? BytesValue {
      get { return bytesValue_; }
      set {
        bytesValue_ = value;
      }
    }


    /// <summary>Field number for the "repeated_bytes" field.</summary>
    public const int RepeatedBytesFieldNumber = 3;
    private static readonly pb::FieldCodec<pb::ByteString> _repeated_repeatedBytes_codec
        = pb::FieldCodec.ForBytes(26);
    private readonly pbc::RepeatedField<pb::ByteString> repeatedBytes_ = new pbc::RepeatedField<pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<pb::ByteString> RepeatedBytes {
      get { return repeatedBytes_; }
    }

    /// <summary>Field number for the "map_bytes" field.</summary>
    public const int MapBytesFieldNumber = 4;
    private static readonly pbc::MapField<string, pb::ByteString>.Codec _map_mapBytes_codec
        = new pbc::MapField<string, pb::ByteString>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForBytes(18, pb::ByteString.Empty), 34);
    private readonly pbc::MapField<string, pb::ByteString> mapBytes_ = new pbc::MapField<string, pb::ByteString>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, pb::ByteString> MapBytes {
      get { return mapBytes_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object? other) {
      return Equals(other as BytesMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(BytesMessage? other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BytesField != other.BytesField) return false;
      if (BytesValue != other.BytesValue) return false;
      if(!repeatedBytes_.Equals(other.repeatedBytes_)) return false;
      if (!MapBytes.Equals(other.MapBytes)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BytesField.Length != 0) hash ^= BytesField.GetHashCode();
      if (bytesValue_ != null) hash ^= BytesValue.GetHashCode();
      hash ^= repeatedBytes_.GetHashCode();
      hash ^= MapBytes.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BytesField.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(BytesField);
      }
      if (bytesValue_ != null) {
        _single_bytesValue_codec.WriteTagAndValue(output, BytesValue);
      }
      repeatedBytes_.WriteTo(output, _repeated_repeatedBytes_codec);
      mapBytes_.WriteTo(output, _map_mapBytes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BytesField.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(BytesField);
      }
      if (bytesValue_ != null) {
        _single_bytesValue_codec.WriteTagAndValue(ref output, BytesValue);
      }
      repeatedBytes_.WriteTo(ref output, _repeated_repeatedBytes_codec);
      mapBytes_.WriteTo(ref output, _map_mapBytes_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BytesField.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BytesField);
      }
      if (bytesValue_ != null) {
        size += _single_bytesValue_codec.CalculateSizeWithTag(BytesValue);
      }
      size += repeatedBytes_.CalculateSize(_repeated_repeatedBytes_codec);
      size += mapBytes_.CalculateSize(_map_mapBytes_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(BytesMessage? other) {
      if (other == null) {
        return;
      }
      if (other.BytesField.Length != 0) {
        BytesField = other.BytesField;
      }
      if (other.bytesValue_ != null) {
        if (bytesValue_ == null || other.BytesValue != pb::ByteString.Empty) {
          BytesValue = other.BytesValue;
        }
      }
      repeatedBytes_.Add(other.repeatedBytes_);
      mapBytes_.MergeFrom(other.mapBytes_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            BytesField = input.ReadBytes();
            break;
          }
          case 18: {
            pb::ByteString value = _single_bytesValue_codec.Read(input);
            if (bytesValue_ == null || value != pb::ByteString.Empty) {
              BytesValue = value;
            }
            break;
          }
          case 26: {
            repeatedBytes_.AddEntriesFrom(input, _repeated_repeatedBytes_codec);
            break;
          }
          case 34: {
            mapBytes_.AddEntriesFrom(input, _map_mapBytes_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            BytesField = input.ReadBytes();
            break;
          }
          case 18: {
            pb::ByteString value = _single_bytesValue_codec.Read(ref input);
            if (bytesValue_ == null || value != pb::ByteString.Empty) {
              BytesValue = value;
            }
            break;
          }
          case 26: {
            repeatedBytes_.AddEntriesFrom(ref input, _repeated_repeatedBytes_codec);
            break;
          }
          case 34: {
            mapBytes_.AddEntriesFrom(ref input, _map_mapBytes_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
