#nullable enable annotations

// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/ComplexMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufNrtAnnotator.Tests.Protos {

  /// <summary>Holder for reflection information generated from Protos/ComplexMessage.proto</summary>
  public static partial class ComplexMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/ComplexMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ComplexMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChtQcm90b3MvQ29tcGxleE1lc3NhZ2UucHJvdG8SIVByb3RvYnVmTnJ0QW5u",
            "b3RhdG9yLlRlc3RzLlByb3RvcxoeZ29vZ2xlL3Byb3RvYnVmL3dyYXBwZXJz",
            "LnByb3RvIq0ECg5Db21wbGV4TWVzc2FnZRIMCgRuYW1lGAEgASgJEg8KBWVt",
            "YWlsGAIgASgJSAASDwoFcGhvbmUYAyABKAlIABINCgNmYXgYBCABKAVIABIM",
            "CgR0YWdzGAUgAygJEg4KBnNjb3JlcxgGIAMoBRIrCgVub3RlcxgHIAMoCzIc",
            "Lmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRJVCgphdHRyaWJ1dGVzGAgg",
            "AygLMkEuUHJvdG9idWZOcnRBbm5vdGF0b3IuVGVzdHMuUHJvdG9zLkNvbXBs",
            "ZXhNZXNzYWdlLkF0dHJpYnV0ZXNFbnRyeRJRCghjaGlsZHJlbhgJIAMoCzI/",
            "LlByb3RvYnVmTnJ0QW5ub3RhdG9yLlRlc3RzLlByb3Rvcy5Db21wbGV4TWVz",
            "c2FnZS5DaGlsZHJlbkVudHJ5EkAKBm5lc3RlZBgKIAEoCzIwLlByb3RvYnVm",
            "TnJ0QW5ub3RhdG9yLlRlc3RzLlByb3Rvcy5OZXN0ZWRNZXNzYWdlGjEKD0F0",
            "dHJpYnV0ZXNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgB",
            "GmIKDUNoaWxkcmVuRW50cnkSCwoDa2V5GAEgASgFEkAKBXZhbHVlGAIgASgL",
            "MjEuUHJvdG9idWZOcnRBbm5vdGF0b3IuVGVzdHMuUHJvdG9zLkNvbXBsZXhN",
            "ZXNzYWdlOgI4AUIOCgxjb250YWN0X2luZm8iJAoNTmVzdGVkTWVzc2FnZRIT",
            "CgtkZXNjcmlwdGlvbhgBIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage), global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage.Parser, new[]{ "Name", "Email", "Phone", "Fax", "Tags", "Scores", "Notes", "Attributes", "Children", "Nested" }, new[]{ "ContactInfo" }, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage), global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage.Parser, new[]{ "Description" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ComplexMessage : pb::IMessage<ComplexMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ComplexMessage> _parser = new pb::MessageParser<ComplexMessage>(() => new ComplexMessage());
    private pb::UnknownFieldSet? _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ComplexMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComplexMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComplexMessage(ComplexMessage other) : this() {
      name_ = other.name_;
      tags_ = other.tags_.Clone();
      scores_ = other.scores_.Clone();
      notes_ = other.notes_.Clone();
      attributes_ = other.attributes_.Clone();
      children_ = other.children_.Clone();
      nested_ = other.nested_ != null ? other.nested_.Clone() : null;
      switch (other.ContactInfoCase) {
        case ContactInfoOneofCase.Email:
          Email = other.Email;
          break;
        case ContactInfoOneofCase.Phone:
          Phone = other.Phone;
          break;
        case ContactInfoOneofCase.Fax:
          Fax = other.Fax;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ComplexMessage Clone() {
      return new ComplexMessage(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    /// <summary>
    /// Standard field
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Email {
      get { return HasEmail ? (string) contactInfo_ : ""; }
      set {
        contactInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        contactInfoCase_ = ContactInfoOneofCase.Email;
      }
    }
    /// <summary>Gets whether the "email" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEmail {
      get { return contactInfoCase_ == ContactInfoOneofCase.Email; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "email" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEmail() {
      if (HasEmail) {
        ClearContactInfo();
      }
    }

    /// <summary>Field number for the "phone" field.</summary>
    public const int PhoneFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Phone {
      get { return HasPhone ? (string) contactInfo_ : ""; }
      set {
        contactInfo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        contactInfoCase_ = ContactInfoOneofCase.Phone;
      }
    }
    /// <summary>Gets whether the "phone" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPhone {
      get { return contactInfoCase_ == ContactInfoOneofCase.Phone; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "phone" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPhone() {
      if (HasPhone) {
        ClearContactInfo();
      }
    }

    /// <summary>Field number for the "fax" field.</summary>
    public const int FaxFieldNumber = 4;
    /// <summary>
    /// Value type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Fax {
      get { return HasFax ? (int) contactInfo_ : 0; }
      set {
        contactInfo_ = value;
        contactInfoCase_ = ContactInfoOneofCase.Fax;
      }
    }
    /// <summary>Gets whether the "fax" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasFax {
      get { return contactInfoCase_ == ContactInfoOneofCase.Fax; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "fax" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearFax() {
      if (HasFax) {
        ClearContactInfo();
      }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 5;
    private static readonly pb::FieldCodec<string> _repeated_tags_codec
        = pb::FieldCodec.ForString(42);
    private readonly pbc::RepeatedField<string> tags_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// Repeated fields
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Tags {
      get { return tags_; }
    }

    /// <summary>Field number for the "scores" field.</summary>
    public const int ScoresFieldNumber = 6;
    private static readonly pb::FieldCodec<int> _repeated_scores_codec
        = pb::FieldCodec.ForInt32(50);
    private readonly pbc::RepeatedField<int> scores_ = new pbc::RepeatedField<int>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<int> Scores {
      get { return scores_; }
    }

    /// <summary>Field number for the "notes" field.</summary>
    public const int NotesFieldNumber = 7;
    private static readonly pb::FieldCodec<string> _repeated_notes_codec
        = pb::FieldCodec.ForClassWrapper<string>(58);
    private readonly pbc::RepeatedField<string> notes_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Notes {
      get { return notes_; }
    }

    /// <summary>Field number for the "attributes" field.</summary>
    public const int AttributesFieldNumber = 8;
    private static readonly pbc::MapField<string, string>.Codec _map_attributes_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 66);
    private readonly pbc::MapField<string, string> attributes_ = new pbc::MapField<string, string>();
    /// <summary>
    /// Map fields
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Attributes {
      get { return attributes_; }
    }

    /// <summary>Field number for the "children" field.</summary>
    public const int ChildrenFieldNumber = 9;
    private static readonly pbc::MapField<int, global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage>.Codec _map_children_codec
        = new pbc::MapField<int, global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage.Parser), 74);
    private readonly pbc::MapField<int, global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage> children_ = new pbc::MapField<int, global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessage> Children {
      get { return children_; }
    }

    /// <summary>Field number for the "nested" field.</summary>
    public const int NestedFieldNumber = 10;
    private global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage nested_;
    /// <summary>
    /// Nested message
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage? Nested {
      get { return nested_; }
      set {
        nested_ = value;
      }
    }

    private object contactInfo_;
    /// <summary>Enum of possible cases for the "contact_info" oneof.</summary>
    public enum ContactInfoOneofCase {
      None = 0,
      Email = 2,
      Phone = 3,
      Fax = 4,
    }
    private ContactInfoOneofCase contactInfoCase_ = ContactInfoOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContactInfoOneofCase ContactInfoCase {
      get { return contactInfoCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearContactInfo() {
      contactInfoCase_ = ContactInfoOneofCase.None;
      contactInfo_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object? other) {
      return Equals(other as ComplexMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ComplexMessage? other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Email != other.Email) return false;
      if (Phone != other.Phone) return false;
      if (Fax != other.Fax) return false;
      if(!tags_.Equals(other.tags_)) return false;
      if(!scores_.Equals(other.scores_)) return false;
      if(!notes_.Equals(other.notes_)) return false;
      if (!Attributes.Equals(other.Attributes)) return false;
      if (!Children.Equals(other.Children)) return false;
      if (!object.Equals(Nested, other.Nested)) return false;
      if (ContactInfoCase != other.ContactInfoCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (HasEmail) hash ^= Email.GetHashCode();
      if (HasPhone) hash ^= Phone.GetHashCode();
      if (HasFax) hash ^= Fax.GetHashCode();
      hash ^= tags_.GetHashCode();
      hash ^= scores_.GetHashCode();
      hash ^= notes_.GetHashCode();
      hash ^= Attributes.GetHashCode();
      hash ^= Children.GetHashCode();
      if (nested_ != null) hash ^= Nested.GetHashCode();
      hash ^= (int) contactInfoCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasEmail) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (HasPhone) {
        output.WriteRawTag(26);
        output.WriteString(Phone);
      }
      if (HasFax) {
        output.WriteRawTag(32);
        output.WriteInt32(Fax);
      }
      tags_.WriteTo(output, _repeated_tags_codec);
      scores_.WriteTo(output, _repeated_scores_codec);
      notes_.WriteTo(output, _repeated_notes_codec);
      attributes_.WriteTo(output, _map_attributes_codec);
      children_.WriteTo(output, _map_children_codec);
      if (nested_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Nested);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasEmail) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (HasPhone) {
        output.WriteRawTag(26);
        output.WriteString(Phone);
      }
      if (HasFax) {
        output.WriteRawTag(32);
        output.WriteInt32(Fax);
      }
      tags_.WriteTo(ref output, _repeated_tags_codec);
      scores_.WriteTo(ref output, _repeated_scores_codec);
      notes_.WriteTo(ref output, _repeated_notes_codec);
      attributes_.WriteTo(ref output, _map_attributes_codec);
      children_.WriteTo(ref output, _map_children_codec);
      if (nested_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Nested);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasEmail) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (HasPhone) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Phone);
      }
      if (HasFax) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Fax);
      }
      size += tags_.CalculateSize(_repeated_tags_codec);
      size += scores_.CalculateSize(_repeated_scores_codec);
      size += notes_.CalculateSize(_repeated_notes_codec);
      size += attributes_.CalculateSize(_map_attributes_codec);
      size += children_.CalculateSize(_map_children_codec);
      if (nested_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Nested);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ComplexMessage? other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      tags_.Add(other.tags_);
      scores_.Add(other.scores_);
      notes_.Add(other.notes_);
      attributes_.MergeFrom(other.attributes_);
      children_.MergeFrom(other.children_);
      if (other.nested_ != null) {
        if (nested_ == null) {
          Nested = new global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage();
        }
        Nested.MergeFrom(other.Nested);
      }
      switch (other.ContactInfoCase) {
        case ContactInfoOneofCase.Email:
          Email = other.Email;
          break;
        case ContactInfoOneofCase.Phone:
          Phone = other.Phone;
          break;
        case ContactInfoOneofCase.Fax:
          Fax = other.Fax;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 26: {
            Phone = input.ReadString();
            break;
          }
          case 32: {
            Fax = input.ReadInt32();
            break;
          }
          case 42: {
            tags_.AddEntriesFrom(input, _repeated_tags_codec);
            break;
          }
          case 50:
          case 48: {
            scores_.AddEntriesFrom(input, _repeated_scores_codec);
            break;
          }
          case 58: {
            notes_.AddEntriesFrom(input, _repeated_notes_codec);
            break;
          }
          case 66: {
            attributes_.AddEntriesFrom(input, _map_attributes_codec);
            break;
          }
          case 74: {
            children_.AddEntriesFrom(input, _map_children_codec);
            break;
          }
          case 82: {
            if (nested_ == null) {
              Nested = new global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage();
            }
            input.ReadMessage(Nested);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 26: {
            Phone = input.ReadString();
            break;
          }
          case 32: {
            Fax = input.ReadInt32();
            break;
          }
          case 42: {
            tags_.AddEntriesFrom(ref input, _repeated_tags_codec);
            break;
          }
          case 50:
          case 48: {
            scores_.AddEntriesFrom(ref input, _repeated_scores_codec);
            break;
          }
          case 58: {
            notes_.AddEntriesFrom(ref input, _repeated_notes_codec);
            break;
          }
          case 66: {
            attributes_.AddEntriesFrom(ref input, _map_attributes_codec);
            break;
          }
          case 74: {
            children_.AddEntriesFrom(ref input, _map_children_codec);
            break;
          }
          case 82: {
            if (nested_ == null) {
              Nested = new global::ProtobufNrtAnnotator.Tests.Protos.NestedMessage();
            }
            input.ReadMessage(Nested);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class NestedMessage : pb::IMessage<NestedMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<NestedMessage> _parser = new pb::MessageParser<NestedMessage>(() => new NestedMessage());
    private pb::UnknownFieldSet? _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<NestedMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNrtAnnotator.Tests.Protos.ComplexMessageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NestedMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NestedMessage(NestedMessage other) : this() {
      description_ = other.description_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public NestedMessage Clone() {
      return new NestedMessage(this);
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 1;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object? other) {
      return Equals(other as NestedMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(NestedMessage? other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Description != other.Description) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Description.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Description.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Description);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(NestedMessage? other) {
      if (other == null) {
        return;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Description = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
