// Nullable annotations added by ProtobufNrtAnnotator
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/EnumsMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

#nullable enable annotations

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufNrtAnnotator.Tests.Protos {

  /// <summary>Holder for reflection information generated from Protos/EnumsMessage.proto</summary>
  public static partial class EnumsMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/EnumsMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EnumsMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlQcm90b3MvRW51bXNNZXNzYWdlLnByb3RvEiFQcm90b2J1Zk5ydEFubm90",
            "YXRvci5UZXN0cy5Qcm90b3MingMKDEVudW1zTWVzc2FnZRI/CgplbnVtX3Zh",
            "bHVlGAEgASgOMisuUHJvdG9idWZOcnRBbm5vdGF0b3IuVGVzdHMuUHJvdG9z",
            "LlRlc3RFbnVtEkIKDXJlcGVhdGVkX2VudW0YAiADKA4yKy5Qcm90b2J1Zk5y",
            "dEFubm90YXRvci5UZXN0cy5Qcm90b3MuVGVzdEVudW0SVQoRbmVzdGVkX2Vu",
            "dW1fdmFsdWUYAyABKA4yOi5Qcm90b2J1Zk5ydEFubm90YXRvci5UZXN0cy5Q",
            "cm90b3MuRW51bXNNZXNzYWdlLk5lc3RlZEVudW0SWAoUcmVwZWF0ZWRfbmVz",
            "dGVkX2VudW0YBCADKA4yOi5Qcm90b2J1Zk5ydEFubm90YXRvci5UZXN0cy5Q",
            "cm90b3MuRW51bXNNZXNzYWdlLk5lc3RlZEVudW0iWAoKTmVzdGVkRW51bRIb",
            "ChdORVNURURfRU5VTV9VTlNQRUNJRklFRBAAEhUKEU5FU1RFRF9FTlVNX0ZJ",
            "UlNUEAESFgoSTkVTVEVEX0VOVU1fU0VDT05EEAIqUAoIVGVzdEVudW0SGQoV",
            "VEVTVF9FTlVNX1VOU1BFQ0lGSUVEEAASEwoPVEVTVF9FTlVNX0ZJUlNUEAES",
            "FAoQVEVTVF9FTlVNX1NFQ09ORBACYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ProtobufNrtAnnotator.Tests.Protos.TestEnum), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage), global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Parser, new[]{ "EnumValue", "RepeatedEnum", "NestedEnumValue", "RepeatedNestedEnum" }, null, new[]{ typeof(global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum) }, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TestEnum {
    [pbr::OriginalName("TEST_ENUM_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("TEST_ENUM_FIRST")] First = 1,
    [pbr::OriginalName("TEST_ENUM_SECOND")] Second = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class EnumsMessage : pb::IMessage<EnumsMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<EnumsMessage> _parser = new pb::MessageParser<EnumsMessage>(() => new EnumsMessage());
    private pb::UnknownFieldSet? _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<EnumsMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnumsMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnumsMessage(EnumsMessage other) : this() {
      enumValue_ = other.enumValue_;
      repeatedEnum_ = other.repeatedEnum_.Clone();
      nestedEnumValue_ = other.nestedEnumValue_;
      repeatedNestedEnum_ = other.repeatedNestedEnum_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public EnumsMessage Clone() {
      return new EnumsMessage(this);
    }

    /// <summary>Field number for the "enum_value" field.</summary>
    public const int EnumValueFieldNumber = 1;
    private global::ProtobufNrtAnnotator.Tests.Protos.TestEnum enumValue_ = global::ProtobufNrtAnnotator.Tests.Protos.TestEnum.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtobufNrtAnnotator.Tests.Protos.TestEnum EnumValue {
      get { return enumValue_; }
      set {
        enumValue_ = value;
      }
    }

    /// <summary>Field number for the "repeated_enum" field.</summary>
    public const int RepeatedEnumFieldNumber = 2;
    private static readonly pb::FieldCodec<global::ProtobufNrtAnnotator.Tests.Protos.TestEnum> _repeated_repeatedEnum_codec
        = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::ProtobufNrtAnnotator.Tests.Protos.TestEnum) x);
    private readonly pbc::RepeatedField<global::ProtobufNrtAnnotator.Tests.Protos.TestEnum> repeatedEnum_ = new pbc::RepeatedField<global::ProtobufNrtAnnotator.Tests.Protos.TestEnum>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtobufNrtAnnotator.Tests.Protos.TestEnum> RepeatedEnum {
      get { return repeatedEnum_; }
    }

    /// <summary>Field number for the "nested_enum_value" field.</summary>
    public const int NestedEnumValueFieldNumber = 3;
    private global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum nestedEnumValue_ = global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum.Unspecified;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum NestedEnumValue {
      get { return nestedEnumValue_; }
      set {
        nestedEnumValue_ = value;
      }
    }

    /// <summary>Field number for the "repeated_nested_enum" field.</summary>
    public const int RepeatedNestedEnumFieldNumber = 4;
    private static readonly pb::FieldCodec<global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum> _repeated_repeatedNestedEnum_codec
        = pb::FieldCodec.ForEnum(34, x => (int) x, x => (global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum) x);
    private readonly pbc::RepeatedField<global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum> repeatedNestedEnum_ = new pbc::RepeatedField<global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum> RepeatedNestedEnum {
      get { return repeatedNestedEnum_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object? other) {
      return Equals(other as EnumsMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(EnumsMessage? other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EnumValue != other.EnumValue) return false;
      if(!repeatedEnum_.Equals(other.repeatedEnum_)) return false;
      if (NestedEnumValue != other.NestedEnumValue) return false;
      if(!repeatedNestedEnum_.Equals(other.repeatedNestedEnum_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (EnumValue != global::ProtobufNrtAnnotator.Tests.Protos.TestEnum.Unspecified) hash ^= EnumValue.GetHashCode();
      hash ^= repeatedEnum_.GetHashCode();
      if (NestedEnumValue != global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum.Unspecified) hash ^= NestedEnumValue.GetHashCode();
      hash ^= repeatedNestedEnum_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (EnumValue != global::ProtobufNrtAnnotator.Tests.Protos.TestEnum.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EnumValue);
      }
      repeatedEnum_.WriteTo(output, _repeated_repeatedEnum_codec);
      if (NestedEnumValue != global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) NestedEnumValue);
      }
      repeatedNestedEnum_.WriteTo(output, _repeated_repeatedNestedEnum_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (EnumValue != global::ProtobufNrtAnnotator.Tests.Protos.TestEnum.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EnumValue);
      }
      repeatedEnum_.WriteTo(ref output, _repeated_repeatedEnum_codec);
      if (NestedEnumValue != global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum.Unspecified) {
        output.WriteRawTag(24);
        output.WriteEnum((int) NestedEnumValue);
      }
      repeatedNestedEnum_.WriteTo(ref output, _repeated_repeatedNestedEnum_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (EnumValue != global::ProtobufNrtAnnotator.Tests.Protos.TestEnum.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EnumValue);
      }
      size += repeatedEnum_.CalculateSize(_repeated_repeatedEnum_codec);
      if (NestedEnumValue != global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) NestedEnumValue);
      }
      size += repeatedNestedEnum_.CalculateSize(_repeated_repeatedNestedEnum_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(EnumsMessage? other) {
      if (other == null) {
        return;
      }
      if (other.EnumValue != global::ProtobufNrtAnnotator.Tests.Protos.TestEnum.Unspecified) {
        EnumValue = other.EnumValue;
      }
      repeatedEnum_.Add(other.repeatedEnum_);
      if (other.NestedEnumValue != global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum.Unspecified) {
        NestedEnumValue = other.NestedEnumValue;
      }
      repeatedNestedEnum_.Add(other.repeatedNestedEnum_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            EnumValue = (global::ProtobufNrtAnnotator.Tests.Protos.TestEnum) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            repeatedEnum_.AddEntriesFrom(input, _repeated_repeatedEnum_codec);
            break;
          }
          case 24: {
            NestedEnumValue = (global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum) input.ReadEnum();
            break;
          }
          case 34:
          case 32: {
            repeatedNestedEnum_.AddEntriesFrom(input, _repeated_repeatedNestedEnum_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            EnumValue = (global::ProtobufNrtAnnotator.Tests.Protos.TestEnum) input.ReadEnum();
            break;
          }
          case 18:
          case 16: {
            repeatedEnum_.AddEntriesFrom(ref input, _repeated_repeatedEnum_codec);
            break;
          }
          case 24: {
            NestedEnumValue = (global::ProtobufNrtAnnotator.Tests.Protos.EnumsMessage.Types.NestedEnum) input.ReadEnum();
            break;
          }
          case 34:
          case 32: {
            repeatedNestedEnum_.AddEntriesFrom(ref input, _repeated_repeatedNestedEnum_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the EnumsMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum NestedEnum {
        [pbr::OriginalName("NESTED_ENUM_UNSPECIFIED")] Unspecified = 0,
        [pbr::OriginalName("NESTED_ENUM_FIRST")] First = 1,
        [pbr::OriginalName("NESTED_ENUM_SECOND")] Second = 2,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
