// Nullable annotations added by ProtobufNrtAnnotator
// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/WrappersMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

#nullable enable annotations

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtobufNrtAnnotator.Tests.Protos {

  /// <summary>Holder for reflection information generated from Protos/WrappersMessage.proto</summary>
  public static partial class WrappersMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for Protos/WrappersMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WrappersMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChxQcm90b3MvV3JhcHBlcnNNZXNzYWdlLnByb3RvEiFQcm90b2J1Zk5ydEFu",
            "bm90YXRvci5UZXN0cy5Qcm90b3MaHmdvb2dsZS9wcm90b2J1Zi93cmFwcGVy",
            "cy5wcm90byLZAwoPV3JhcHBlcnNNZXNzYWdlEjIKDGRvdWJsZV92YWx1ZRgB",
            "IAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5Eb3VibGVWYWx1ZRIwCgtmbG9hdF92",
            "YWx1ZRgCIAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5GbG9hdFZhbHVlEjAKC2lu",
            "dDY0X3ZhbHVlGAMgASgLMhsuZ29vZ2xlLnByb3RvYnVmLkludDY0VmFsdWUS",
            "MgoMdWludDY0X3ZhbHVlGAQgASgLMhwuZ29vZ2xlLnByb3RvYnVmLlVJbnQ2",
            "NFZhbHVlEjAKC2ludDMyX3ZhbHVlGAUgASgLMhsuZ29vZ2xlLnByb3RvYnVm",
            "LkludDMyVmFsdWUSMgoMdWludDMyX3ZhbHVlGAYgASgLMhwuZ29vZ2xlLnBy",
            "b3RvYnVmLlVJbnQzMlZhbHVlEi4KCmJvb2xfdmFsdWUYByABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuQm9vbFZhbHVlEjIKDHN0cmluZ192YWx1ZRgIIAEoCzIc",
            "Lmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIwCgtieXRlc192YWx1ZRgJ",
            "IAEoCzIbLmdvb2dsZS5wcm90b2J1Zi5CeXRlc1ZhbHVlYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.WrappersReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtobufNrtAnnotator.Tests.Protos.WrappersMessage), global::ProtobufNrtAnnotator.Tests.Protos.WrappersMessage.Parser, new[]{ "DoubleValue", "FloatValue", "Int64Value", "Uint64Value", "Int32Value", "Uint32Value", "BoolValue", "StringValue", "BytesValue" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class WrappersMessage : pb::IMessage<WrappersMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<WrappersMessage> _parser = new pb::MessageParser<WrappersMessage>(() => new WrappersMessage());
    private pb::UnknownFieldSet? _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<WrappersMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtobufNrtAnnotator.Tests.Protos.WrappersMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrappersMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrappersMessage(WrappersMessage other) : this() {
      DoubleValue = other.DoubleValue;
      FloatValue = other.FloatValue;
      Int64Value = other.Int64Value;
      Uint64Value = other.Uint64Value;
      Int32Value = other.Int32Value;
      Uint32Value = other.Uint32Value;
      BoolValue = other.BoolValue;
      StringValue = other.StringValue;
      BytesValue = other.BytesValue;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WrappersMessage Clone() {
      return new WrappersMessage(this);
    }

    /// <summary>Field number for the "double_value" field.</summary>
    public const int DoubleValueFieldNumber = 1;
    private static readonly pb::FieldCodec<double?> _single_doubleValue_codec = pb::FieldCodec.ForStructWrapper<double>(10);
    private double? doubleValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double? DoubleValue {
      get { return doubleValue_; }
      set {
        doubleValue_ = value;
      }
    }


    /// <summary>Field number for the "float_value" field.</summary>
    public const int FloatValueFieldNumber = 2;
    private static readonly pb::FieldCodec<float?> _single_floatValue_codec = pb::FieldCodec.ForStructWrapper<float>(18);
    private float? floatValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float? FloatValue {
      get { return floatValue_; }
      set {
        floatValue_ = value;
      }
    }


    /// <summary>Field number for the "int64_value" field.</summary>
    public const int Int64ValueFieldNumber = 3;
    private static readonly pb::FieldCodec<long?> _single_int64Value_codec = pb::FieldCodec.ForStructWrapper<long>(26);
    private long? int64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long? Int64Value {
      get { return int64Value_; }
      set {
        int64Value_ = value;
      }
    }


    /// <summary>Field number for the "uint64_value" field.</summary>
    public const int Uint64ValueFieldNumber = 4;
    private static readonly pb::FieldCodec<ulong?> _single_uint64Value_codec = pb::FieldCodec.ForStructWrapper<ulong>(34);
    private ulong? uint64Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong? Uint64Value {
      get { return uint64Value_; }
      set {
        uint64Value_ = value;
      }
    }


    /// <summary>Field number for the "int32_value" field.</summary>
    public const int Int32ValueFieldNumber = 5;
    private static readonly pb::FieldCodec<int?> _single_int32Value_codec = pb::FieldCodec.ForStructWrapper<int>(42);
    private int? int32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int? Int32Value {
      get { return int32Value_; }
      set {
        int32Value_ = value;
      }
    }


    /// <summary>Field number for the "uint32_value" field.</summary>
    public const int Uint32ValueFieldNumber = 6;
    private static readonly pb::FieldCodec<uint?> _single_uint32Value_codec = pb::FieldCodec.ForStructWrapper<uint>(50);
    private uint? uint32Value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint? Uint32Value {
      get { return uint32Value_; }
      set {
        uint32Value_ = value;
      }
    }


    /// <summary>Field number for the "bool_value" field.</summary>
    public const int BoolValueFieldNumber = 7;
    private static readonly pb::FieldCodec<bool?> _single_boolValue_codec = pb::FieldCodec.ForStructWrapper<bool>(58);
    private bool? boolValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool? BoolValue {
      get { return boolValue_; }
      set {
        boolValue_ = value;
      }
    }


    /// <summary>Field number for the "string_value" field.</summary>
    public const int StringValueFieldNumber = 8;
    private static readonly pb::FieldCodec<string> _single_stringValue_codec = pb::FieldCodec.ForClassWrapper<string>(66);
    private string? stringValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string? StringValue {
      get { return stringValue_; }
      set {
        stringValue_ = value;
      }
    }


    /// <summary>Field number for the "bytes_value" field.</summary>
    public const int BytesValueFieldNumber = 9;
    private static readonly pb::FieldCodec<pb::ByteString> _single_bytesValue_codec = pb::FieldCodec.ForClassWrapper<pb::ByteString>(74);
    private pb::ByteString? bytesValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pb::ByteString? BytesValue {
      get { return bytesValue_; }
      set {
        bytesValue_ = value;
      }
    }


    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object? other) {
      return Equals(other as WrappersMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(WrappersMessage? other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.Equals(DoubleValue, other.DoubleValue)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
      if (Int64Value != other.Int64Value) return false;
      if (Uint64Value != other.Uint64Value) return false;
      if (Int32Value != other.Int32Value) return false;
      if (Uint32Value != other.Uint32Value) return false;
      if (BoolValue != other.BoolValue) return false;
      if (StringValue != other.StringValue) return false;
      if (BytesValue != other.BytesValue) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (doubleValue_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableDoubleEqualityComparer.GetHashCode(DoubleValue);
      if (floatValue_ != null) hash ^= pbc::ProtobufEqualityComparers.BitwiseNullableSingleEqualityComparer.GetHashCode(FloatValue);
      if (int64Value_ != null) hash ^= Int64Value.GetHashCode();
      if (uint64Value_ != null) hash ^= Uint64Value.GetHashCode();
      if (int32Value_ != null) hash ^= Int32Value.GetHashCode();
      if (uint32Value_ != null) hash ^= Uint32Value.GetHashCode();
      if (boolValue_ != null) hash ^= BoolValue.GetHashCode();
      if (stringValue_ != null) hash ^= StringValue.GetHashCode();
      if (bytesValue_ != null) hash ^= BytesValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (doubleValue_ != null) {
        _single_doubleValue_codec.WriteTagAndValue(output, DoubleValue);
      }
      if (floatValue_ != null) {
        _single_floatValue_codec.WriteTagAndValue(output, FloatValue);
      }
      if (int64Value_ != null) {
        _single_int64Value_codec.WriteTagAndValue(output, Int64Value);
      }
      if (uint64Value_ != null) {
        _single_uint64Value_codec.WriteTagAndValue(output, Uint64Value);
      }
      if (int32Value_ != null) {
        _single_int32Value_codec.WriteTagAndValue(output, Int32Value);
      }
      if (uint32Value_ != null) {
        _single_uint32Value_codec.WriteTagAndValue(output, Uint32Value);
      }
      if (boolValue_ != null) {
        _single_boolValue_codec.WriteTagAndValue(output, BoolValue);
      }
      if (stringValue_ != null) {
        _single_stringValue_codec.WriteTagAndValue(output, StringValue);
      }
      if (bytesValue_ != null) {
        _single_bytesValue_codec.WriteTagAndValue(output, BytesValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (doubleValue_ != null) {
        _single_doubleValue_codec.WriteTagAndValue(ref output, DoubleValue);
      }
      if (floatValue_ != null) {
        _single_floatValue_codec.WriteTagAndValue(ref output, FloatValue);
      }
      if (int64Value_ != null) {
        _single_int64Value_codec.WriteTagAndValue(ref output, Int64Value);
      }
      if (uint64Value_ != null) {
        _single_uint64Value_codec.WriteTagAndValue(ref output, Uint64Value);
      }
      if (int32Value_ != null) {
        _single_int32Value_codec.WriteTagAndValue(ref output, Int32Value);
      }
      if (uint32Value_ != null) {
        _single_uint32Value_codec.WriteTagAndValue(ref output, Uint32Value);
      }
      if (boolValue_ != null) {
        _single_boolValue_codec.WriteTagAndValue(ref output, BoolValue);
      }
      if (stringValue_ != null) {
        _single_stringValue_codec.WriteTagAndValue(ref output, StringValue);
      }
      if (bytesValue_ != null) {
        _single_bytesValue_codec.WriteTagAndValue(ref output, BytesValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (doubleValue_ != null) {
        size += _single_doubleValue_codec.CalculateSizeWithTag(DoubleValue);
      }
      if (floatValue_ != null) {
        size += _single_floatValue_codec.CalculateSizeWithTag(FloatValue);
      }
      if (int64Value_ != null) {
        size += _single_int64Value_codec.CalculateSizeWithTag(Int64Value);
      }
      if (uint64Value_ != null) {
        size += _single_uint64Value_codec.CalculateSizeWithTag(Uint64Value);
      }
      if (int32Value_ != null) {
        size += _single_int32Value_codec.CalculateSizeWithTag(Int32Value);
      }
      if (uint32Value_ != null) {
        size += _single_uint32Value_codec.CalculateSizeWithTag(Uint32Value);
      }
      if (boolValue_ != null) {
        size += _single_boolValue_codec.CalculateSizeWithTag(BoolValue);
      }
      if (stringValue_ != null) {
        size += _single_stringValue_codec.CalculateSizeWithTag(StringValue);
      }
      if (bytesValue_ != null) {
        size += _single_bytesValue_codec.CalculateSizeWithTag(BytesValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(WrappersMessage? other) {
      if (other == null) {
        return;
      }
      if (other.doubleValue_ != null) {
        if (doubleValue_ == null || other.DoubleValue != 0D) {
          DoubleValue = other.DoubleValue;
        }
      }
      if (other.floatValue_ != null) {
        if (floatValue_ == null || other.FloatValue != 0F) {
          FloatValue = other.FloatValue;
        }
      }
      if (other.int64Value_ != null) {
        if (int64Value_ == null || other.Int64Value != 0L) {
          Int64Value = other.Int64Value;
        }
      }
      if (other.uint64Value_ != null) {
        if (uint64Value_ == null || other.Uint64Value != 0UL) {
          Uint64Value = other.Uint64Value;
        }
      }
      if (other.int32Value_ != null) {
        if (int32Value_ == null || other.Int32Value != 0) {
          Int32Value = other.Int32Value;
        }
      }
      if (other.uint32Value_ != null) {
        if (uint32Value_ == null || other.Uint32Value != 0) {
          Uint32Value = other.Uint32Value;
        }
      }
      if (other.boolValue_ != null) {
        if (boolValue_ == null || other.BoolValue != false) {
          BoolValue = other.BoolValue;
        }
      }
      if (other.stringValue_ != null) {
        if (stringValue_ == null || other.StringValue != "") {
          StringValue = other.StringValue;
        }
      }
      if (other.bytesValue_ != null) {
        if (bytesValue_ == null || other.BytesValue != pb::ByteString.Empty) {
          BytesValue = other.BytesValue;
        }
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            double? value = _single_doubleValue_codec.Read(input);
            if (doubleValue_ == null || value != 0D) {
              DoubleValue = value;
            }
            break;
          }
          case 18: {
            float? value = _single_floatValue_codec.Read(input);
            if (floatValue_ == null || value != 0F) {
              FloatValue = value;
            }
            break;
          }
          case 26: {
            long? value = _single_int64Value_codec.Read(input);
            if (int64Value_ == null || value != 0L) {
              Int64Value = value;
            }
            break;
          }
          case 34: {
            ulong? value = _single_uint64Value_codec.Read(input);
            if (uint64Value_ == null || value != 0UL) {
              Uint64Value = value;
            }
            break;
          }
          case 42: {
            int? value = _single_int32Value_codec.Read(input);
            if (int32Value_ == null || value != 0) {
              Int32Value = value;
            }
            break;
          }
          case 50: {
            uint? value = _single_uint32Value_codec.Read(input);
            if (uint32Value_ == null || value != 0) {
              Uint32Value = value;
            }
            break;
          }
          case 58: {
            bool? value = _single_boolValue_codec.Read(input);
            if (boolValue_ == null || value != false) {
              BoolValue = value;
            }
            break;
          }
          case 66: {
            string value = _single_stringValue_codec.Read(input);
            if (stringValue_ == null || value != "") {
              StringValue = value;
            }
            break;
          }
          case 74: {
            pb::ByteString value = _single_bytesValue_codec.Read(input);
            if (bytesValue_ == null || value != pb::ByteString.Empty) {
              BytesValue = value;
            }
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            double? value = _single_doubleValue_codec.Read(ref input);
            if (doubleValue_ == null || value != 0D) {
              DoubleValue = value;
            }
            break;
          }
          case 18: {
            float? value = _single_floatValue_codec.Read(ref input);
            if (floatValue_ == null || value != 0F) {
              FloatValue = value;
            }
            break;
          }
          case 26: {
            long? value = _single_int64Value_codec.Read(ref input);
            if (int64Value_ == null || value != 0L) {
              Int64Value = value;
            }
            break;
          }
          case 34: {
            ulong? value = _single_uint64Value_codec.Read(ref input);
            if (uint64Value_ == null || value != 0UL) {
              Uint64Value = value;
            }
            break;
          }
          case 42: {
            int? value = _single_int32Value_codec.Read(ref input);
            if (int32Value_ == null || value != 0) {
              Int32Value = value;
            }
            break;
          }
          case 50: {
            uint? value = _single_uint32Value_codec.Read(ref input);
            if (uint32Value_ == null || value != 0) {
              Uint32Value = value;
            }
            break;
          }
          case 58: {
            bool? value = _single_boolValue_codec.Read(ref input);
            if (boolValue_ == null || value != false) {
              BoolValue = value;
            }
            break;
          }
          case 66: {
            string value = _single_stringValue_codec.Read(ref input);
            if (stringValue_ == null || value != "") {
              StringValue = value;
            }
            break;
          }
          case 74: {
            pb::ByteString value = _single_bytesValue_codec.Read(ref input);
            if (bytesValue_ == null || value != pb::ByteString.Empty) {
              BytesValue = value;
            }
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
